source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'VaporChat' do
use_frameworks!

pod 'Starscream', '~> 4.0.0'
pod 'SnapKit'
pod 'SwiftyJSON'
pod 'Kingfisher'

#pod 'TSVoiceConverter'
pod 'Alamofire'
pod 'ReactiveCocoa'
#pod 'YYKit'
pod 'Timepiece'

end
