source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'VaporChat' do
use_frameworks!

#  pod 'TimedSilver'
#  pod 'JRefresh' #代替 MJRefresh
#  pod 'arek' #管理系统的权限
# 上面的库是不支持Swift5.0的 只能拖进去工程自己编译

  pod 'Starscream', '~> 4.0.0' #代替 SocketRocket
  pod 'SnapKit' #代替 Masonry
  pod 'SwiftyJSON' #json数据 自动对可选择进行拆包
  pod 'Kingfisher' #代替 SDWebImage
  pod 'Alamofire' #代替 AFNetworking
  pod 'ReactiveCocoa' #RAC Swift版本
  pod 'Timepiece' #时间管理器
  pod 'NVActivityIndicatorView' #loading炫酷动画
  
  pod 'FileKit'
  pod 'UIColor_Hex_Swift'
  pod "BSImagePicker"
  pod 'XLActionController'
  pod 'SQLite.swift' #代替 FMDB
#  pod 'TSVoiceConverter' #音频格式转换
  pod 'ObjectMapper' #可以帮助我们快速的进行各个类型和Json类型的相互转换

#  pod 'Valet' #管理keychain钥匙串
#  pod 'PromiseKit' #异步变同步写法
#  pod 'Hero' #自定义试图控制器过渡动画
#  pod 'CryptoSwift' #加密


#GDPerformanceView在状态栏上方显示 FPS，CPU 使用情况，app 和 iOS 版本，并通过 delegate 报告 FPS 和 CPU 使用情况。
#Spring 做动画更简单、可链和声明

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
